apiVersion: v1
kind: Service
metadata:
  name: easyshop-hack-service
  namespace: easyshop-hack
  labels:
    name: easyshop-hack-service
    environment: production
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
  selector:
    app: easyshop-hack-app