apiVersion: v1
kind: PersistentVolume
metadata:
  name: easy-mongodb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb
  persistentVolumeReclaimPolicy: Retain