apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: easy-mongodb-pvc
  namespace: easyshop-hack
  labels:
    name: easy-mongodb-pvc
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi